//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import "MMUIViewControllerDelegate.h"

@class CContact, NSArray, NSDictionary;

@protocol ContactSelectViewDelegate <MMUIViewControllerDelegate>
- (void)onSelectContact:(CContact *)arg1;

@optional
- (void)onContactSelectSearchSections:(NSArray *)arg1 sectionTitles:(NSDictionary *)arg2 sectionResults:(NSDictionary *)arg3;
- (BOOL)onFilterContactCandidate:(CContact *)contact;
- (void)onSelectBrandContact;
- (void)onSelectHistoryGroup;
- (void)onSelectRadarCreateRoom;
- (BOOL)onShouldSelectContact:(CContact *)contact;
@end

