//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#import "MMTableViewDelegate.h"

@class MMTableViewCellInfo, NSIndexPath;

@protocol MMTableViewInfoDelegate <NSObject, UIScrollViewDelegate, MMTableViewDelegate>

@optional
- (void)commitEditingForRowAtIndexPath:(NSIndexPath *)arg1 Cell:(MMTableViewCellInfo *)arg2;
- (void)accessoryButtonTappedForRowWithIndexPath:(NSIndexPath *)arg1 Cell:(MMTableViewCellInfo *)arg2;
@end

